version: "3.8"

services:
  db:
    image: postgres:17.5-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: metasim
      POSTGRES_PASSWORD: 5633
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: metasim-service-demo
    ports:
      - "443:42000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
